Controllers/QuestionController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp1.Models;


namespace WebApp1.Controllers
{ //This view shows questions relating to the associated quiz based on it's share QuizId.
  public class QuestionController : Controller
  {
    QuestionDataContext objQuestionDataContext = new QuestionDataContext();

   
    public ActionResult QuestionQ(int Id)
   
    {
      var Questions = (from eachQ in objQuestionDataContext.Questions select eachQ).Where(s => s.Quiz2Id == Id).ToList();


      return View(objQuestionDataContext.Questions.Where(s => s.Quiz2Id == Id).ToList());
    }

    //Question view for Restricted user with no answers
    public ActionResult QuestionQRestrict(int Id)
    
    {
      var Questions = (from eachQ in objQuestionDataContext.Questions select eachQ).Where(s => s.Quiz2Id == Id).ToList();


      return View(objQuestionDataContext.Questions.Where(s => s.Quiz2Id == Id).ToList());
    }
    //Question view For view user with no edit permissions.
    public ActionResult QuestionQView(int Id)
   
    {
      var Questions = (from eachQ in objQuestionDataContext.Questions select eachQ).Where(s => s.Quiz2Id == Id).ToList();


      return View(objQuestionDataContext.Questions.Where(s => s.Quiz2Id == Id).ToList());
    }

    // question details view of all questions
    public IActionResult QuestionDetails()

    {


      var QuizList = (from eachQ in objQuestionDataContext.Questions select eachQ).ToList();


      return View(objQuestionDataContext.Questions.ToList());
    }

    // create new question view
    public ActionResult create()
    {

      return View();
    }

    //post of question
    [HttpPost]
    public ActionResult create(Question objQ)
    {

      objQuestionDataContext.Questions.Add(objQ);
      objQuestionDataContext.SaveChanges();
      return Redirect("QuestionDetails");
    }
  
    
    //Details view of selected question
    public ActionResult Details(string id)
    {
      int QId = Convert.ToInt32(id);
      var objQ = objQuestionDataContext.Questions.Find(QId);
      return View(objQ);
    }

    //Details question view for view user
    public ActionResult ViewUserDetails(string id)
    {
      int QId = Convert.ToInt32(id);
      var objQ = objQuestionDataContext.Questions.Find(QId);
      return View(objQ);
    }
    // Admin detail view
    public ActionResult ViewAdminDetails(string id)
    {
      int QId = Convert.ToInt32(id);
      var objQ = objQuestionDataContext.Questions.Find(QId);
      return View(objQ);
    }

    //question edit view
    public ActionResult Edit(int id)
    {
      int QId = Convert.ToInt32(id);
      var objQ = objQuestionDataContext.Questions.Find(QId);
      return View(objQ);
    }

    //post questions
    [HttpPost]
    public ActionResult Edit(Question objQ)
    {
      var data = objQuestionDataContext.Questions.Find(objQ.QuestionId);
      if (data != null)
      {
        data.QuestionId = objQ.QuestionId;
        data.Q = objQ.Q;
        data.Choice1 = objQ.Choice1;
        data.Choice2 = objQ.Choice2;
        data.Choice3 = objQ.Choice3;
        data.Choice4 = objQ.Choice4;
        data.Choice5 = objQ.Choice5;
        data.Answer = objQ.Answer;
        data.Quiz2Id = objQ.Quiz2Id;
      }
      objQuestionDataContext.SaveChanges();
      return Redirect("QuestionDetails"); 
    }

    //delete question view
    public ActionResult Delete(int id)
    {
      int QId = Convert.ToInt32(id);
      var Q = objQuestionDataContext.Questions.Find(QId);
      return View(Q);
    }

    //post of delete questions
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
      var quiz = await objQuestionDataContext.Questions.FindAsync(id);
      objQuestionDataContext.Questions.Remove(quiz);
      await objQuestionDataContext.SaveChangesAsync();
      return View(); 
    }

    private bool QuizExists(int id)
    {
      return objQuestionDataContext.Quiz2s.Any(e => e.Quiz2Id == id);
    }

  
  }
}

Controllers/Quiz2Controller.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApp1.Models;

namespace WebApp1.Controllers
{// Controls the quiz view.
  public class Quiz2Controller : Controller
  {
   QuestionDataContext Quiz2DataContext = new QuestionDataContext();

    //Initial page to show all quizzes
    public IActionResult Index()
    {
      List<Quiz2> Quiz2 = Quiz2DataContext.Quiz2s.ToList();
      return View(Quiz2);
     
    }
    //Create new quiz view
    public ActionResult create()
    {

      return View();
    }


    // GET: Quiz2/Create
    [HttpPost]
    public ActionResult create(Quiz2 objQuiz)
    {
      Quiz2DataContext.Quiz2s.Add(objQuiz);
      Quiz2DataContext.SaveChanges();
      return View();
    }
    public ActionResult Details(int? id)
    {


     

      Quiz2 quiz = Quiz2DataContext.Quiz2s
    .Include(a => a.Questions)
    .Where(a => a.Quiz2Id == id)
    .SingleOrDefault();

      if (quiz == null)
      {
        return NotFound();
      }

      var view = new QuizwithQDetaillView
      {
        Quiz2Id = quiz.Quiz2Id,
        QuizTitle = quiz.QuizTitle,
        Questions=quiz.Questions.ToList()
      };

        return View(view);
      }
    //edit quiz view
  public ActionResult Edit(string id)
    {
      int quiz2Id = Convert.ToInt32(id);
      var quiz2 = Quiz2DataContext.Quiz2s.Find(quiz2Id);
      return View(quiz2);
    }
    //posts edit of quiz
    [HttpPost]
    public ActionResult Edit(Quiz2 objQuiz)
    {
      var data = Quiz2DataContext.Quiz2s.Find(objQuiz.Quiz2Id);
      if (data != null)
      {
        data.Quiz2Id = objQuiz.Quiz2Id;
        data.QuizTitle = objQuiz.QuizTitle;
        
      }
      Quiz2DataContext.SaveChanges();
      return View();
    }
    //delete quiz view
    public ActionResult Delete(string id)
    {
      int quiz2Id = Convert.ToInt32(id);
      var quiz2 = Quiz2DataContext.Quiz2s.Find(quiz2Id);
      return View(quiz2);
    }
  }
}

Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp1.Data;
using WebApp1.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;


namespace WebApp1.Controllers
{
  public class RoleController : Controller
  {
    RoleManager<IdentityRole> roleManager;

    public RoleController(RoleManager<IdentityRole> roleManager)
    {
      this.roleManager = roleManager;
    }

    [Authorize(Policy = "readpolicy")]
    public IActionResult Index()
    {
      var roles = roleManager.Roles.ToList();
      return View(roles);
    }

    [Authorize(Policy = "writepolicy")]
    public IActionResult Create()
    {
      return View(new IdentityRole());
    }

    [HttpPost]
    public async Task<IActionResult> Create(IdentityRole role)
    {
      await roleManager.CreateAsync(role);
      return RedirectToAction("Index");
    }
  }
}

Controllers/ViewUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp1.Data;
using WebApp1.Models;

namespace WebApp1.Controllers
{// Using permissioning for manager aka view user to see questions and answers. Most of these views will not be utlised and only the Question controller will be used as this user can only see questions and answers. 
  [Authorize(Roles = "Manager")]
  public class ViewUserController : Controller
    {
    QuestionDataContext Quiz2DataContext = new QuestionDataContext();

    //This is the initial view the user sees and controls what the user will be able to see and redirects to the question controller in the html page. 
    public IActionResult Index()
    {
      List<Quiz2> Quiz2 = Quiz2DataContext.Quiz2s.ToList();
      return View(Quiz2);
   
    }

    public ActionResult create()
    {

      return View();
    }


    // GET: Quiz2b/Create
    [HttpPost]
    public ActionResult create(Quiz2 objQuiz)
    {
      Quiz2DataContext.Quiz2s.Add(objQuiz);
      Quiz2DataContext.SaveChanges();
      return View();
    }
    public ActionResult Details(int? id)
    {




      Quiz2 quiz = Quiz2DataContext.Quiz2s
    .Include(a => a.Questions)
    .Where(a => a.Quiz2Id == id)
    .SingleOrDefault();

      if (quiz == null)
      {
        return NotFound();
      }

      var view = new QuizwithQDetaillView
      {
        Quiz2Id = quiz.Quiz2Id,
        QuizTitle = quiz.QuizTitle,
        Questions = quiz.Questions.ToList()
      };

      return View(view);
    }

    public ActionResult Edit(string id)
    {
      int quiz2Id = Convert.ToInt32(id);
      var quiz2 = Quiz2DataContext.Quiz2s.Find(quiz2Id);
      return View(quiz2);
    }

    [HttpPost]
    public ActionResult Edit(Quiz2 objQuiz)
    {
      var data = Quiz2DataContext.Quiz2s.Find(objQuiz.Quiz2Id);
      if (data != null)
      {
        data.Quiz2Id = objQuiz.Quiz2Id;
        data.QuizTitle = objQuiz.QuizTitle;

      }
      Quiz2DataContext.SaveChanges();
      return View();
    }

    public ActionResult Delete(string id)
    {
      int quiz2Id = Convert.ToInt32(id);
      var quiz2 = Quiz2DataContext.Quiz2s.Find(quiz2Id);
      return View(quiz2);
    }
  }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Quiz Manager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
              <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> Quiz Manager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                  <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                      <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin Quiz View</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link text-dark" asp-area="" asp-controller="ViewUser" asp-action="Index">View User Quiz View</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link text-dark" asp-area="" asp-controller="RestrictedUser" asp-action="Index">Restricted User Quiz View</a>
                    </li>
                    @*<li class="nav-item">
                      <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                    </li>*@
                    @*<li class="nav-item">
                      <a class="nav-link text-dark" asp-area="" asp-controller="Question" asp-action="QuestionDetails">Questions</a>
                    </li>*@
                    @*<li class="nav-item">
                      <a class="nav-link text-dark" asp-area="" asp-controller="Quiz2" asp-action="Index" id="=UrlParameter.Optional">Quizzes</a>
                    </li>*@
                   </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
      <div class="container">
        &copy; 2021 - WebbiSkools Ltd @*- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
      </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>